name: Test Build

on:
#  push:
#    branches:
#      - main
#  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Build With Gradle
        run: |
          echo "BUILD_TIME=$(TZ=Asia/Shanghai date "+%Y%m%d%H%M")" >> $GITHUB_ENV
          sudo apt install python3 -y
          chmod +x gradlew
          ./gradlew assemblerelease --build-cache --parallel --daemon --warning-mode all
          
      - name: Prepare App
        run: |
          mkdir -p ${{ github.workspace }}/apk/
          for file in `find ~ -name "*.apk" -print`; do
            mv "$file" ${{ github.workspace }}/apk/
          done
      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v2.2.1
        if: startsWith(takagen99-Box-${{ env.BUILD_TIME }}, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: takagen99-Box-${{ env.BUILD_TIME }}
          name: takagen99-Box-${{ env.BUILD_TIME }}
          body: 'takagen99-Box-${{ env.BUILD_TIME }}'
          draft: false
          prerelease: false
          files: |
            ${{ github.workspace }}/apk/*
            
      - name: Upload App To Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: com.github.tvbox.osc
          path: ${{ github.workspace }}/apk/*     
